/*data types in java
 * 
 * 1. primitive data types
 * 2. non -primitive data types
 * 
 * the primitive data types include boolean , char ,byte, short, int, long , float, and double.
 * the non primitive data types: the non primitive data types include Classes, Interfaces and Arrays.
 * 
 * 
boolean data type:  boolean have values like false and true , and default size of boolean is 1 bit.
char datatype : default alue of char is '\u0000' and default size of char datatype is 2 byte.
byte datatype: default value of byte data type is 0 and default size of byte datatype is 1 byte,
short datatype: default value of short datatype is o and default size of short datatype is 2 byte.
int datatype: default value of int datatype is 0, and default size of int datatype is 4 byte.
long datatype:default value of long datatype is 0L, and default size of long datatype is 8 byte,
float datatype; default value of float datatype is 0.0f , and default size of float datatype is 4 byte.
double datatype: default value of double datatype is 0.0d, and size is 8 byte


why char uses 2 bytes in java and what is '\u0000'?
it is because java uses unicode system not ascii value , the \u0000 is the lowest value of unicodesystem, 

what is the unicode system?
unicode is the universal international standard character encoding that is capable of representing most of the world's written language.

why java uses unicoe system?
before unicode , there were many language standard :

ASCII (American Standard Code for Information Interchange) for the United States.
ISO 8859-1 for Western European Language.
KOI-8 for Russian.
GB18030 and BIG-5 for chinese, and so on.

operator in java:

There are many types of operators in Java which are given below:

Unary Operator,
Arithmetic Operator,
Shift Operator,
Relational Operator,
Bitwise Operator,
Logical Operator,
Ternary Operator and
Assignment Operator.

java keyword :

list of java keywords:
1.abstract;
java abstract keywords is useful to declare an abstract class, an abstract class can provide the mplementation of interface, it can have abstract and non abstract methos.

2. boolean :
java boolean keywords is used to declare a variable as a boolean type, it can hold true and false value only.

3. break:
java break keyword is used to break the loop or switch element.it break the current flow of the program 

4. byte:
java byte keyword is used to declared a variable which can hold 8 bit data balue.

5. catch: Java catch keyword is used to catch the exceptions generated by try statements. It must be used after the try block only.

6. char: Java char keyword is used to declare a variable that can hold unsigned 16-bit Unicode characters

7. class: java class keyword is used to declare a class .

8. enum: enum is basically used to define the fixed set of constant , enum constructor are always private or default.

 9. extends: Java extends keyword is used to indicate that a class is derived from another class or interface.

 10. final: final keyword is used to indicate that a variable holds a constant value , it is used with a variable , it is used to restrict the variable from upating the variable value.
 
 */
